apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "p1-bigquery-exporter.fullname" . }}
  labels:
    {{- include "p1-bigquery-exporter.labels" . | nindent 4 }}
data:
  p1-device-path: {{ .Values.cronjob.usbDevice | quote }}
  bq-enable: {{ .Values.config.bqEnable | quote }}
  bq-project-id: {{ .Values.config.bqProjectID | quote }}
  bq-dataset: {{ .Values.config.bqDataset | quote }}
  bq-table: {{ .Values.config.bqTable | quote }}
  config.yaml: |
    {{- with .Values.config.configYaml }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}