# Default values for p1-bigquery-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  usbDevice: /dev/ttyUSB0

config:
  bqEnable: false
  bqProjectID: gcp-project-id
  bqDataset: my-dataset
  bqTable: my-table
  configYaml: |
    supportedReadings:
      # 1-0:1.8.1(123456.789*kWh)
      - prefix: 1-0:1.8.1
        name: Levering dal
        unit: Wh
        valueMultiplier: 1000
        valueStartIndex: 10
        valueLength: 10
      # 1-0:1.8.2(123456.789*kWh)
      - prefix: 1-0:1.8.2
        name: Levering normaal
        unit: Wh
        valueMultiplier: 1000
        valueStartIndex: 10
        valueLength: 10

      # 1-0:2.8.1(123456.789*kWh)
      - prefix: 1-0:2.8.1
        name: Teruglevering dal
        unit: Wh
        valueMultiplier: -1000
        valueStartIndex: 10
        valueLength: 10
      # 1-0:2.8.2(123456.789*kWh)
      - prefix: 1-0:2.8.2
        name: Teruglevering normaal
        unit: Wh
        valueMultiplier: -1000
        valueStartIndex: 10
        valueLength: 10

      # 1-0:1.7.0(01.193*kW)
      - prefix: 1-0:1.7.0
        name: Levering vermogen
        unit: W
        valueMultiplier: 1000
        valueStartIndex: 10
        valueLength: 6
      # 1-0:2.7.0(00.000*kW)
      - prefix: 1-0:2.7.0
        name: Teruglevering vermogen
        unit: W
        valueMultiplier: -1000
        valueStartIndex: 10
        valueLength: 6

      # 0-1:24.2.1(101209112500W)(12785.123*m3)
      - prefix: 0-1:24.2.1
        name: Levering gas
        unit: m3
        valueMultiplier: 1
        valueStartIndex: 26
        valueLength: 9

secret:
  gcpServiceAccountKeyfile: '{}'

logFormat: json

image:
  repository: jsalverda/p1-bigquery-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # Specifies whether roles and bindings should be created
  enable: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
