apiVersion: v1
kind: Namespace
metadata:
  name: p1-bigquery-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: p1-bigquery-exporter-configs
  namespace: p1-bigquery-exporter
  labels:
    app: p1-bigquery-exporter
data:
  p1-device-path: ${P1_DEVICE_PATH}
  bq-enable: '${BQ_ENABLE}'
  bq-project-id: ${BQ_PROJECT_ID}
  bq-dataset: ${BQ_DATASET}
  bq-table: ${BQ_TABLE}
  config.yaml: |
    supportedReadings:
    # 1-0:1.8.1(123456.789*kWh)
    - prefix: 1-0:1.8.1
      name: Levering dal
      unit: Wh
      valueMultiplier: 1000
      valueStartIndex: 10
      valueLength: 10
    # 1-0:1.8.2(123456.789*kWh)
    - prefix: 1-0:1.8.2
      name: Levering normaal
      unit: Wh
      valueMultiplier: 1000
      valueStartIndex: 10
      valueLength: 10

    # 1-0:2.8.1(123456.789*kWh)
    - prefix: 1-0:2.8.1
      name: Teruglevering dal
      unit: Wh
      valueMultiplier: -1000
      valueStartIndex: 10
      valueLength: 10
    # 1-0:2.8.2(123456.789*kWh)
    - prefix: 1-0:2.8.2
      name: Teruglevering normaal
      unit: Wh
      valueMultiplier: -1000
      valueStartIndex: 10
      valueLength: 10

    # 1-0:1.7.0(01.193*kW)
    - prefix: 1-0:1.7.0
      name: Levering vermogen
      unit: W
      valueMultiplier: 1000
      valueStartIndex: 10
      valueLength: 6
    # 1-0:2.7.0(00.000*kW)
    - prefix: 1-0:2.7.0
      name: Teruglevering vermogen
      unit: W
      valueMultiplier: -1000
      valueStartIndex: 10
      valueLength: 6

    # 0-1:24.2.1(101209112500W)(12785.123*m3)
    - prefix: 0-1:24.2.1
      name: Levering gas
      unit: m3
      valueMultiplier: 1
      valueStartIndex: 26
      valueLength: 9