apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: p1-bigquery-exporter
  namespace: p1-bigquery-exporter
  labels:
    app: p1-bigquery-exporter
spec:
  schedule: '${SCHEDULE}'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  suspend: false  
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: p1-bigquery-exporter
        spec:
          restartPolicy: OnFailure
          containers:
          - name: p1-bigquery-exporter
            image: jsalverda/p1-bigquery-exporter:${CONTAINER_TAG}
            env:
            - name: P1_DEVICE_PATH
              valueFrom:
                configMapKeyRef:
                  key: p1-device-path
                  name: p1-bigquery-exporter-configs
            - name: BQ_ENABLE
              valueFrom:
                configMapKeyRef:
                  key: bq-enable
                  name: p1-bigquery-exporter-configs
            - name: BQ_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  key: bq-project-id
                  name: p1-bigquery-exporter-configs
            - name: BQ_DATASET
              valueFrom:
                configMapKeyRef:
                  key: bq-dataset
                  name: p1-bigquery-exporter-configs
            - name: BQ_TABLE
              valueFrom:
                configMapKeyRef:
                  key: bq-table
                  name: p1-bigquery-exporter-configs
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/keyfile.json
            resources:
              requests:
                cpu: 100m
                memory: 200Mi
              limits:
                cpu: 200m
                memory: 200Mi
            securityContext:
              privileged: true
            volumeMounts:
            - name: configs
              mountPath: /configs
            - name: secrets
              mountPath: /secrets
            - name: usb
              mountPath: ${P1_DEVICE_PATH}
          terminationGracePeriodSeconds: 300
          volumes:
          - name: configs
            configMap:
              name: p1-bigquery-exporter-configs
          - name: secrets
            secret:
              defaultMode: 420
              secretName: p1-bigquery-exporter-credentials
          - name: usb
            hostPath:
              path: ${P1_DEVICE_PATH}