apiVersion: v1
kind: Namespace
metadata:
  name: p1-bigquery-exporter
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: p1-bigquery-exporter
  namespace: p1-bigquery-exporter
  labels:
    app: p1-bigquery-exporter
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - configmaps
  verbs:
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: p1-bigquery-exporter
  namespace: p1-bigquery-exporter
  labels:
    app: p1-bigquery-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: p1-bigquery-exporter
subjects:
- kind: ServiceAccount
  name: p1-bigquery-exporter
  namespace: p1-bigquery-exporter