apiVersion: v1
kind: Namespace
metadata:
  name: p1-bigquery-exporter
---
apiVersion: v1
kind: Secret
metadata:
  name: p1-bigquery-exporter-credentials
  namespace: p1-bigquery-exporter
  labels:
    app: p1-bigquery-exporter
type: Opaque
data:
  keyfile.json: ${GCP_SERVICE_ACCOUNT_KEYFILE}